"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.api = void 0;
var express = require("express");
var admin_1 = require("./admin/admin");
var todo_1 = require("./todo");
var auth_1 = require("./auth");
// import { PasswordRouter } from './password';
var payment_1 = require("./payment");
var twilio_1 = require("./twilio");
var middleware_1 = require("../services/middleware");
var email_1 = require("./email");
var chat_1 = require("./chat");
var file_1 = require("./file");
var review_1 = require("./review");
var user_1 = require("./user");
var aws_1 = require("./aws");
var jwPlayer_1 = require("./jwPlayer");
var refunds_1 = require("./refunds");
var fcmTokens_1 = require("./fcmTokens");
var inviteUser_1 = require("./inviteUser");
var api_log_1 = require("../services/api.log");
var error_log_1 = require("../services/error.log");
var autoComplete_1 = require("./autoComplete");
var superAdmin_1 = require("./superAdmin");
var products_1 = require("./products");
var orders_1 = require("./orders");
var utils_1 = require("./utils");
var referrals_1 = require("./referrals");
var subscription_1 = require("./subscription");
var middleware = new middleware_1.Middleware();
exports.api = express.Router();
exports.api.use(middleware.jwtDecoder);
exports.api.use('/admin', new admin_1.AdminRouter().router);
exports.api.use('/todo', new todo_1.TodoRouter().router);
exports.api.use('/superAdmin', new superAdmin_1.SuperAdminRouter().router);
// api.use('/password', new PasswordRouter().router);
exports.api.use('/auth', new auth_1.AuthRouter().router);
exports.api.use('/payment', new payment_1.PaymentRouter().router);
exports.api.use('/subscription', new subscription_1.StripeSubscriptionRouter().router);
exports.api.use('/twilio', new twilio_1.TwilioRouter().router);
exports.api.use('/email', new email_1.EmailRouter().router);
exports.api.use('/chat', new chat_1.ChatRouter().router);
exports.api.use('/file', new file_1.FileRouter().router);
exports.api.use('/review', new review_1.ReviewRouter().router);
exports.api.use('/user', new user_1.UserRouter().router);
exports.api.use('/aws', new aws_1.AwsRouter().router);
exports.api.use('/jw-player', new jwPlayer_1.JWPlayerRouter().router);
exports.api.use('/inviteUser', new inviteUser_1.InviteUserRouter().router);
exports.api.use('/accept-invite', new inviteUser_1.AcceptInviteRouter().router);
exports.api.use('/refund', new refunds_1.RefundRouter().router);
exports.api.use('/fcm-token', new fcmTokens_1.FcmTokensRouter().router);
exports.api.use('/autoComplete', new autoComplete_1.AutoCompleteRouter().router);
exports.api.use('/products', new products_1.ProductsRouter().router);
exports.api.use('/orders', new orders_1.OrderRouter().router);
exports.api.use('/utils', new utils_1.UtilsRouter().router);
exports.api.use('/referrals', new referrals_1.ReferralRouter().router);
exports.api.use(api_log_1.ApiLogServices.apiLog);
exports.api.use(error_log_1.ErrorLogServices.errorLog);
//# sourceMappingURL=api.js.map